version: "2.1"
services:
    influxdb:
        image: hypriot/rpi-influxdb
        ports:
            - 8086:8086
        volumes:
            - ./influxdata:/data
            - ./influxdatabackup:/root/databackup
    grafana:
        image: fg2it/grafana-armhf:v4.1.1
        ports:
            - 3000:3000
        volumes:
            - ./grafanadata/
